
source 'https://rubygems.org'

gem 'currency_utils', path: '../../gems/currency_utils'
# Declare your gem's dependencies in customers.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec
